"""Added index for token into RegToken

Revision ID: 350e45d9bf3c
Revises: daac7809466d
Create Date: 2020-10-06 17:56:42.054289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350e45d9bf3c'
down_revision = 'daac7809466d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reg_token', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_reg_token_token'), 'reg_token', ['token'], unique=False)
    op.drop_index('ix_reg_token_email', table_name='reg_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reg_token_email', 'reg_token', ['email'], unique=False)
    op.drop_index(op.f('ix_reg_token_token'), table_name='reg_token')
    op.alter_column('reg_token', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
