"""Added column expired_at to RegToken

Revision ID: 9f9e734716ab
Revises: c0d877680203
Create Date: 2020-10-06 17:23:23.412710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9e734716ab'
down_revision = 'c0d877680203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reg_token', sa.Column('expired_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reg_token', 'expired_at')
    # ### end Alembic commands ###
